import Head from 'next/head'
import NavBar from './Navbar'
import Footer from './Footer'

function Layout({children}) {
    return ( 
        <>
           <Head>
                <title>tuContapp</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
             </Head>
             <NavBar/>
                {children}
             <Footer/>
        </>
     );
}

export default Layout;